/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dgt;

import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author david
 */
public class Examen extends javax.swing.JFrame {
    public List <Pregunta> listaPreguntasEx ;
    public int cont = 0;
    public int nPreguntas = 10;
    /**
     * Creates new form Exam
     */
    public Examen() {
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File ("c:\\"));
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos CSV","csv"));
        chooser.showOpenDialog(this);
        File archivo = chooser.getSelectedFile();
        initComponents();
        Preguntas preguntas = new Preguntas(archivo.getPath());
        listaPreguntasEx = preguntas.getLista();
        refresh();
    }

    public void finalizar(){
        int contB = 0;
        int contM = 0;
        int contN = 0;
            for(int a=0;a<listaPreguntasEx.size();a++){
                Pregunta p = listaPreguntasEx.get(a);
                String rc = p.getRc();
                String rd = p.getRd();
                if(rd != null){
                    if(rd.equals(String.valueOf(rc))){contB++;}
                    else{contM++;}
                }
                else{contN++;}
                }
            String porcentaje = String.valueOf(contB+"0");
            int resp;
            if(Integer.parseInt(porcentaje)<90){
                ImageIcon file = new ImageIcon("src\\main\\resources\\mal.png");
                resp = JOptionPane.showConfirmDialog(btnFinalizar, "Aciertos: "+contB+"\nFallos: "+contM+"\nSin responder: "+contN+"\nPorcentaje de acierto: "+porcentaje+"% \n¿Quieres hacer otro test?", "PRUEBA SUSPENSA", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,file);
            }
            else{
                ImageIcon file = new ImageIcon("src\\main\\resources\\guay.png");
                resp = JOptionPane.showConfirmDialog(btnFinalizar, "Aciertos: "+contB+"\nFallos: "+contM+"\nSin responder: "+contN+"\nPorcentaje de acierto: "+porcentaje+"% \n¿Quieres hacer otro test?", "PRUEBA APROBADA", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,file);            }
            if(resp==0){
                this.setVisible(false);  
                }
            else{System.exit(0);}
    }
    
    public void refresh(){
        boolean salir = false;
        if(salir==false){
            if(cont==0){btnMenos.setEnabled(false);}else{btnMenos.setEnabled(true);}
            if(cont==9){btnMas.setEnabled(false);}else{btnMas.setEnabled(true);}
            Pregunta p = listaPreguntasEx.get(cont);
            panelPregunta1.enunciado.setText(p.getEnunciado());
            String ref = p.getRef();
            panelPregunta1.imagen.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\"+ref+".jpg"));
            contador.setText((cont+1)+"/"+(nPreguntas));
            panelPregunta1.btnR1.setText("a) "+p.getR1());
            panelPregunta1.btnR2.setText("b) "+p.getR2());
            panelPregunta1.btnR3.setText("c) "+p.getR3());
            if(p.getRd()!=null){
                if(panelPregunta1.btnR1.getText().substring(3).equals(p.getRd())){panelPregunta1.btnR1.setSelected(true);}
                else if(panelPregunta1.btnR2.getText().substring(3).equals(p.getRd())){panelPregunta1.btnR2.setSelected(true);}
                else if(panelPregunta1.btnR3.getText().substring(3).equals(p.getRd())){panelPregunta1.btnR3.setSelected(true);}
            }
            else{panelPregunta1.buttonGroup1.clearSelection();}
            
        }
    }
    private void escoge(){
        Pregunta p = listaPreguntasEx.get(cont);
        if(panelPregunta1.btnR1.isSelected()){p.setRd(panelPregunta1.btnR1.getText().substring(3));}
        if(panelPregunta1.btnR2.isSelected()){p.setRd(panelPregunta1.btnR2.getText().substring(3));}
        if(panelPregunta1.btnR3.isSelected()){p.setRd(panelPregunta1.btnR3.getText().substring(3));}
    }
    
    public List<Pregunta> getListaPreguntasEx() {
        return listaPreguntasEx;
    }

    public void setListaPreguntasEx(List<Pregunta> listaPreguntasEx) {
        this.listaPreguntasEx = listaPreguntasEx;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPregunta1 = new com.dgt.PanelPregunta();
        btnFinalizar = new javax.swing.JButton();
        contador = new javax.swing.JLabel();
        btnMenos = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnFinalizar.setText("Finalizar");
        btnFinalizar.setToolTipText("Finalizar prueba");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        contador.setText("10/10");

        btnMenos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMenos.setText("<");
        btnMenos.setToolTipText("Anterior Pregunta");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnMas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMas.setText(">");
        btnMas.setToolTipText("Siguiente pregunta");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(btnMenos)
                .addGap(66, 66, 66)
                .addComponent(contador)
                .addGap(61, 61, 61)
                .addComponent(btnMas))
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(btnFinalizar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contador)
                    .addComponent(btnMenos)
                    .addComponent(btnMas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizar)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
    if(cont>0){
        escoge();
        cont--;
        refresh();
    }      
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
    if(cont<9){
        escoge();
        cont++;
        refresh();
    }
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        escoge();
        finalizar();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JLabel contador;
    private com.dgt.PanelPregunta panelPregunta1;
    // End of variables declaration//GEN-END:variables
}
